### ISSUE TITLE
The name of this function is slightly confusing...

### ISSUE THREAD

**Issue by Merinorus** [bgeron/diff-pdf-visually#10]
Hi,

Thank you for this great tool!

I wanted to confirm your comment in the code:
`The name of this function is slightly confusing: it returns whether the PDFs are *not* different.`

Actually, I was looking for other tools, thinking this one wasn't working correctly, before inverting my boolean check.

We seriously need a clear function name \o/

**Comment by bgeron** [comment]
Hi Merinorus,

Thank you! It always makes me happy to hear that something I made is also useful for others.

This is a great point... something like `pdf_similar` would be a much better name! So I renamed the function and kept the old as a deprecated alias :pray: 

Let me know if you find more things like this (though the package is only small I suppose).

Have a great week, Bram
