### ISSUE TITLE
The diff files cannot be accessed..

### ISSUE THREAD

**Issue by zhimin-z** [bgeron/diff-pdf-visually#15]
![image](https://github.com/bgeron/diff-pdf-visually/assets/8592144/e4a87892-32a5-4a76-a614-5eb54fc69729)
Is that possible to redirect the output diff to a specific file rather than a temporary one?

**Comment by adrien-berchet** [comment]
Hi @zhimin-z 
You can use the `--outdir` argument to use a specific empty directory instead of a temporary directory. So then you can inspect the results.
