### ISSUE TITLE
Significant difference in PDF files that look the same.

### ISSUE THREAD

**Issue by Nosterx** [bgeron/diff-pdf-visually#2]
https://drive.google.com/file/d/1-cczG0g2Ge3XV-oZD1iiM63a0x_r64WU/view?usp=sharing
https://drive.google.com/file/d/1lPmEj-KWWteo_V2Shcd847d6YXHqE2wb/view?usp=sharing

Min sig = 43.9278, significant?=True. The PDFs are different. The most different pages are: page 1 (sgf. 43.9278).

**Comment by bgeron** [comment]
Hi Nosterx,

If you run `diff-pdf-visually -v --time 60 a.pdf c.pdf`, you can see the temporary directory files that the tool generates. One of them will be called `diff-1.pdf`, with a greyscale image of the two pages, and marked in red will be the differences. Does that help?

Cheers, Bram

**Comment by Nosterx** [comment]
Oh, it was in readme, how did I miss it? =\ Thank you so much for the answer and the tool.
