### ISSUE TITLE
Dev installation instructions

### ISSUE THREAD

**Issue by toyg** [bgeron/diff-pdf-visually#3]
This package does not contain any instruction for developers. `pip -e ` fails and `setup.py` is missing. 

I guess `poetry` is somehow used, but that's currently a nonstandard tool, so it would be good to have some basic instructions on how to use it to end up with an editable installation of this package.

I am thankful for the useful code, I'm just trying to make it better - please help us help you ;)

**Comment by bgeron** [comment]
Thanks, that's a good idea! Sorry, been a bit busy recently. I'll try to clarify the instructions / make that easier. In the meantime, if you're okay with installing from PyPI, I believe `pip install diff-pdf-visually` works (I have to add `--user` on Linux). How's that for you?

**Comment by bgeron** [comment]
Ah sorry you said editable. I don't currently know :grimacing: Will give it a look after the weekend!

**Comment by bgeron** [comment]
Hi @toyg , thanks for your interest and reporting this! I moved from poetry to hatch — that seems a more standard tool? On the `main` branch there is now a setup.py, and now

```sh
.venv/bin/pip install -e git+https://github.com/bgeron/diff-pdf-visually#egg=diff_pdf_visually
```

works for me. Let me know if it works for you!
