### ISSUE TITLE
Make pdfdiff_pages public and add optional target directory

### ISSUE THREAD

**Issue by levsa** [bgeron/diff-pdf-visually#6]
It would be nice if `pdfdiff_pages()` was callable with an optional target directory, so that one could look at the diff images for instances. You could use [nullcontext](https://docs.python.org/3/library/contextlib.html#contextlib.nullcontext) to handle the two cases.

**Comment by bgeron** [comment]
Hi Levon! Thanks for this idea, I like it. If I have time this weekend I'll give it a go!

**Comment by bgeron** [comment]
I added a `tempdir` argument to `pdfdiff_pages` and released v1.6.0 with it. Does that help with your use case?

**Comment by levsa** [comment]
That's awesome! Thank you for the fast release 💯 

Now I can archive the diff images as artefacts from a Jenkins job that compare pdfs.

**Comment by bgeron** [comment]
Exciting to hear! Have a great week :)
