### ISSUE TITLE
version missing

### ISSUE THREAD

**Issue by Reissner** [bgeron/diff-pdf-visually#9]
Hey!, 
seems to work well at a first glance. 
In the context i need (maven plugin to build from latex) 
i have a lot of converters and need to check the version. 

Could you provide a command line option to display the version? 

Thank you in advance! 

Best Regards, 
Ernst

**Comment by bgeron** [comment]
Done! v1.6.4 now has a `--version` switch. Let me know if it works for you.

Cheers, Bram

**Comment by Reissner** [comment]
Thank you!
